version: "3.9"

services:
  backend:
    extends:
      file: infra/compose.base.yml
      service: backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      args:
        INSTALL_DEV_DEPS: ${BACKEND_INSTALL_DEV_DEPS:-false}
    command: uvicorn apps.backend.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/workspace:delegated
    working_dir: /workspace
    env_file:
      - .env
      - infra/.env.local
    environment:
      PYTHONPATH: /workspace
    ports:
      - "8000:8000"

  db:
    extends:
      file: infra/compose.base.yml
      service: db
    ports:
      - "5432:5432"
    env_file:
      - infra/.env.local

  caddy:
    extends:
      file: infra/compose.base.yml
      service: caddy
    volumes:
      - ./infra/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - infra/.env.local
    ports:
      - "8080:80"

volumes:
  caddy_data:
  caddy_config:
