services:
  backend-tests-unit:
    image: ${BACKEND_IMAGE:-service-template-backend:latest}
    build:
      context: ..
      dockerfile: apps/backend/Dockerfile
      args:
        INSTALL_DEV_DEPS: "true"
    command: pytest -q apps/backend/tests/unit
    working_dir: /app
    env_file:
      - ../.env
    environment:
      PYTHONPATH: /app
      ENVIRONMENT: test
      APP_ENV: test
      DATABASE_URL: sqlite+pysqlite:////app/apps/backend/tests/.tmp/test.db

  tg-bot-tests-unit:
    image: ${TG_BOT_IMAGE:-service-template-tg:latest}
    build:
      context: ..
      dockerfile: apps/tg_bot/Dockerfile
      args:
        INSTALL_DEV_DEPS: "true"
    command: pytest -q apps/tg_bot/tests/unit
    working_dir: /app
    env_file:
      - ../.env
    environment:
      PYTHONPATH: /app

  notifications-worker-tests-unit:
    image: ${NOTIFICATIONS_WORKER_IMAGE:-service-template-notifications_worker:latest}
    build:
      context: ..
      dockerfile: apps/notifications_worker/Dockerfile
      args:
        INSTALL_DEV_DEPS: "true"
    command: pytest -q apps/notifications_worker/tests
    working_dir: /app
    env_file:
      - ../.env
    environment:
      PYTHONPATH: /app

  tooling:
    image: ${TOOLING_IMAGE:-service-template-tooling:latest}
    build:
      context: ..
      dockerfile: apps/backend/Dockerfile
      args:
        INSTALL_DEV_DEPS: "true"
    working_dir: /workspace
    volumes:
      - ../:/workspace:delegated
    env_file:
      - ../.env
