version: "3.9"

x-backend-env: &backend-env
  DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-service}}
  ENVIRONMENT: ${ENVIRONMENT:-local}
  LOG_LEVEL: ${LOG_LEVEL:-info}

services:
  backend:
    image: ${BACKEND_IMAGE:-service-template-backend:latest}
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      args:
        INSTALL_DEV_DEPS: ${BACKEND_INSTALL_DEV_DEPS:-false}
    environment:
      <<: *backend-env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
    expose:
      - "8000"

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-service}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

  caddy:
    image: caddy:2
    depends_on:
      backend:
        condition: service_started
    networks:
      - edge
      - internal
    volumes:
      - caddy_data:/data
      - caddy_config:/config

networks:
  internal:
  edge:

volumes:
  db_data:
  caddy_data:
  caddy_config:
