services:
  frontend:
    image: ${FRONTEND_IMAGE:-service-template-frontend:latest}
    build:
      context: ../apps/frontend
    command: npm run dev -- --host 0.0.0.0 --port 4321
    env_file:
      - ../.env
      - ./.env.frontend
    depends_on:
      backend:
        condition: service_started
    networks:
      - edge
    ports:
      - "4321:4321"
    profiles: ["frontend"]
