# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.0
_src_path: .
author_email: dev@example.com
author_name: Developer
modules: backend,tg_bot
project_description: A microservice project built with service-template framework
project_name: test-sync
python_version: '3.12'
