"""Base generator class for all code generators."""

from abc import ABC, abstractmethod
from pathlib import Path
import subprocess  # noqa: S404

from framework.spec.loader import AllSpecs

GENERATED_HEADER = """\
##############################################################################
# THIS FILE IS GENERATED BY THE FRAMEWORK. DO NOT EDIT MANUALLY.
# CHANGES WILL BE OVERWRITTEN.
##############################################################################

"""


class BaseGenerator(ABC):
    """Base class for all code generators."""

    def __init__(self, specs: AllSpecs, repo_root: Path) -> None:
        """Initialize generator with validated specs."""
        self.specs = specs
        self.repo_root = repo_root

        # Resolve templates dir relative to this file to support both dev and prod structures
        # framework/generators/base.py -> framework/
        self.framework_dir = Path(__file__).resolve().parent.parent
        self.templates_dir = self.framework_dir / "templates" / "codegen"

    @abstractmethod
    def generate(self) -> list[Path]:
        """Generate files and return list of generated paths."""
        ...

    def write_file(self, path: Path, content: str, *, add_header: bool = True) -> None:
        """Write generated content to file with optional header."""
        path.parent.mkdir(parents=True, exist_ok=True)

        final_content = GENERATED_HEADER + content if add_header else content
        path.write_text(final_content)

    def format_file(self, path: Path) -> None:
        """Format generated file with ruff."""
        ruff_format_cmd = ["ruff", "format", "--no-cache", str(path)]
        ruff_check_cmd = ["ruff", "check", "--no-cache", "--fix", str(path)]
        try:
            subprocess.run(ruff_format_cmd, check=True, capture_output=True)  # noqa: S603, S607
            subprocess.run(ruff_check_cmd, check=False, capture_output=True)  # noqa: S603, S607
        except (subprocess.CalledProcessError, FileNotFoundError):
            # ruff not available or failed, skip formatting
            pass
