"""Base generator class for all code generators."""

from abc import ABC, abstractmethod
from functools import cached_property
from pathlib import Path
import subprocess  # noqa: S404
from typing import Any

from jinja2 import Environment, FileSystemLoader

from framework.lib.fs import atomic_write_text
from framework.spec.loader import AllSpecs

GENERATED_HEADER = """\
##############################################################################
# THIS FILE IS GENERATED BY THE FRAMEWORK. DO NOT EDIT MANUALLY.
# CHANGES WILL BE OVERWRITTEN.
##############################################################################

"""


class BaseGenerator(ABC):
    """Base class for all code generators."""

    def __init__(self, specs: AllSpecs, repo_root: Path) -> None:
        """Initialize generator with validated specs."""
        self.specs = specs
        self.repo_root = repo_root

        # Resolve templates dir relative to this file to support both dev and prod structures
        # framework/generators/base.py -> framework/
        self.framework_dir = Path(__file__).resolve().parent.parent
        self.templates_dir = self.framework_dir / "templates" / "codegen"

    @abstractmethod
    def generate(self) -> list[Path]:
        """Generate files and return list of generated paths."""
        ...

    @cached_property
    def env(self) -> Environment:
        """Jinja environment for codegen templates (built once per generator)."""
        return Environment(
            loader=FileSystemLoader(str(self.templates_dir)),
            trim_blocks=True,
            lstrip_blocks=True,
            autoescape=False,  # noqa: S701
        )

    def render_to_file(
        self,
        template_name: str,
        output_file: Path,
        *,
        add_header: bool = True,
        **context: Any,
    ) -> None:
        """Render a codegen template to a file and format it."""
        content = self.env.get_template(template_name).render(**context)
        self.write_file(output_file, content, add_header=add_header)
        self.format_file(output_file)

    def write_file(self, path: Path, content: str, *, add_header: bool = True) -> None:
        """Write generated content to file with optional header."""
        final_content = GENERATED_HEADER + content if add_header else content
        if not final_content.endswith("\n"):
            final_content += "\n"
        atomic_write_text(path, final_content)

    def format_file(self, path: Path) -> None:
        """Format generated file with ruff."""
        ruff = self.repo_root / ".venv" / "bin" / "ruff"
        if not ruff.exists():
            return
        ruff_str = str(ruff)
        ruff_format_cmd = [ruff_str, "format", "--no-cache", str(path)]
        ruff_check_cmd = [ruff_str, "check", "--no-cache", "--fix", str(path)]
        subprocess.run(ruff_format_cmd, check=True, capture_output=True)  # noqa: S603
        subprocess.run(ruff_check_cmd, check=False, capture_output=True)  # noqa: S603
