backend:
  image: ${BACKEND_IMAGE:-service-template-backend:latest}
  build:
    context: ..
    dockerfile: services/backend/Dockerfile
    args:
      INSTALL_DEV_DEPS: ${BACKEND_INSTALL_DEV_DEPS:-false}
  environment:
    <<: *backend-env
  command: ["services/backend/scripts/start.sh"]
  depends_on:
    db:
      condition: service_healthy
  networks:
    - internal
  expose:
    - "8000"
