backend:
  extends:
    file: compose.base.yml
    service: backend
  build:
    context: ..
    dockerfile: services/backend/Dockerfile
    args:
      INSTALL_DEV_DEPS: ${BACKEND_INSTALL_DEV_DEPS:-false}
  command: >-
    bash -lc "./services/backend/scripts/migrate.sh &&
    uvicorn services.backend.src.main:app --host 0.0.0.0 --port 8000 --reload"
  volumes:
    - ../:/workspace:delegated
  working_dir: /workspace
  env_file:
    - ../.env
  environment:
    PYTHONPATH: /workspace
