x-backend-env: &backend-env
  DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:?}:${POSTGRES_PASSWORD:?}@${POSTGRES_HOST:?}:${POSTGRES_PORT:?}/${POSTGRES_DB:?}
  ASYNC_DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:?}:${POSTGRES_PASSWORD:?}@${POSTGRES_HOST:?}:${POSTGRES_PORT:?}/${POSTGRES_DB:?}


services:

  backend:
    image: ${BACKEND_IMAGE:-test_sync-backend:latest}
    build:
      context: ..
      dockerfile: services/backend/Dockerfile
      args:
        INSTALL_DEV_DEPS: ${BACKEND_INSTALL_DEV_DEPS:-false}
    env_file:
      - ../.env
    environment:
      <<: *backend-env
    command: ["services/backend/scripts/start.sh"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
    expose:
      - "8000"



  tg_bot:
    image: ${TG_BOT_IMAGE:-test_sync-tg:latest}
    build:
      context: ..
      dockerfile: services/tg_bot/Dockerfile
    env_file:
      - ../.env
    depends_on:
      backend:
        condition: service_started
    profiles: ["tg"]
    networks:
      - internal







  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-service}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal



  redis:
    image: redis:7-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - internal


  caddy:
    image: caddy:2

    depends_on:
      backend:
        condition: service_started

    networks:
      - edge
      - internal
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      PUBLIC_HOST: ${PUBLIC_HOST:-localhost}

networks:
  internal:
  edge:

volumes:

  db_data:

  caddy_data:
  caddy_config:
