tg_bot:
  image: ${TG_BOT_IMAGE:-service-template-tg:latest}
  build:
    context: ..
    dockerfile: services/tg_bot/Dockerfile
  env_file:
    - ../.env
  depends_on:
    backend:
      condition: service_started
  networks:
    - internal
